<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\Traits\LogsActivity;
use Spatie\Activitylog\LogOptions;
use Mews\Purifier\Facades\Purifier;
use Illuminate\Support\Str;
use Illuminate\Database\Eloquent\Casts\Attribute;

class News extends Model
{
    use HasFactory, LogsActivity;

    protected $fillable = [
        'title',
        'content',
        'photo',
        'place',
    ];

    public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults()
            ->logOnly(['title', 'content', 'photo', 'place'])
            ->logOnlyDirty()
            ->dontSubmitEmptyLogs()
            ->useLogName('Berita')
            ->setDescriptionForEvent(fn(string $eventName) => "Berita {$eventName}");
    }

    /**
     * Returns a sanitized, plain-text excerpt of the content limited to 35 words.
     *
     * The excerpt is generated by cleaning the HTML content, decoding HTML entities, stripping tags, and truncating to 35 words followed by an ellipsis.
     *
     * @return Attribute The computed attribute containing the shortened content.
     */
    public function shortContent(): Attribute
    {
        return Attribute::make(
            get: fn() => trim(
                Str::words(
                    strip_tags(
                        html_entity_decode(Purifier::clean($this->content))
                    ),
                    35,
                    '...'
                )
            )
        );
    }

    /**
     * Returns a sanitized, plain-text excerpt of the content limited to 20 words with an ellipsis.
     *
     * The content is cleaned of HTML, decoded, stripped of tags, and truncated to 20 words for highlighting purposes.
     *
     * @return Attribute The computed attribute containing the shortened content.
     */
    public function shortContentHighlight(): Attribute
    {
        return Attribute::make(
            get: fn() => trim(
                Str::words(
                    strip_tags(
                        html_entity_decode(Purifier::clean($this->content))
                    ),
                    20,
                    '...'
                )
            )
        );
    }
}
